name: Liberación continua
on:
    release: 
        types: created
permissions:
    contents: write
jobs:
    compilar-y-liberar:
        runs-on: ubuntu-latest
        steps: 
            - name: Clonar repositorio
              uses: actions/checkout@v4
            - name: Compilar código
              run: gcc hola_mundo.c -o hola_mundo -O3
            - name: Subir el ejecutable
              uses: svenstaro/upload-release-action@v2
              with:
                file: hola_mundo
                repo_token: ${{ secrets.GITHUB_TOKEN }}

    docker:
      runs-on: ubuntu-latest
      steps: 
        - name: Clonar repositorio
          uses: actions/checkout@v4
        - name: login to docker hun
          uses: docker/login-actions@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: compilar y subir imagen
          uses: docker/build-push-action@v6
          with: 
            context: .
            tags: luiscruz01/taller-git
            push: true